ARG SERVERCORE_VERSION

FROM mcr.microsoft.com/windows/servercore:${SERVERCORE_VERSION} as download
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN $URL = 'https://github.com/thxCode/containernetworking-plugins/releases/download/v0.2.0-rancher/binaries.zip'; \
    \
    Write-Host ('Downloading CNI plugins from {0} ...' -f $URL); \
    \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -UseBasicParsing -OutFile c:\containernetworking-plugins.zip -Uri $URL; \
    \
    Write-Host 'Expanding ...'; \
    \
    Expand-Archive -Force -Path c:\containernetworking-plugins.zip -DestinationPath c:\containernetworking\.; \
    \
    Write-Host 'Complete.';
RUN $URL = 'https://github.com/thxCode/coreos-flannel/releases/download/v0.2.0-rancher/binaries.zip'; \
    \
    Write-Host ('Downloading Flanneld from {0} ...' -f $URL); \
    \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -UseBasicParsing -OutFile c:\flanneld.zip -Uri $URL; \
    \
    Write-Host 'Expanding ...'; \
    \
    Expand-Archive -Force -Path c:\flanneld.zip -DestinationPath c:\flanneld\.; \
    \
    Write-Host 'Complete.';

FROM mcr.microsoft.com/powershell:nanoserver-${SERVERCORE_VERSION}
ENV MODE="overlay"
COPY ["windows/*", "C:/Program Files/runtime/"]
COPY --from=download ["/containernetworking/bin/host-local.exe", "/containernetworking/bin/flannel.exe", "/containernetworking/bin/win-overlay.exe", "/containernetworking/bin/win-bridge.exe", "/flanneld/dist/flanneld.exe", "c:/Program Files/flannel/bin/"]
WORKDIR "C:\\Program Files\\runtime"
CMD ["pwsh.exe", "-f", "copy.ps1"]
